spring.application.name=contact-manager
server.port=8080
logging.level.root=info
spring.datasource.url = jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=
spring.datasource.password=
spring.jpa.generate-ddl=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

spring.security.user.name=sandeep
spring.security.user.password=password

spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=106776640435-.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=GOCSPX-PJczkZuNCbgBmFaA6gaJB0s0427
spring.security.oauth2.client.registration.google.scope=email,profile

jwt.secretKey=asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyi8df7asdf87987g98a7sg986a89sdf7y



